### ISSUE TITLE
Legal Disclaimer

### ISSUE THREAD

**Issue by mpavon66** [TNRIS/flood#100]
There is a sense of urgency in having a disclaimer pup-up with a check box for “acceptance” before the viewer is used.

The text should be something like:

**"The intent of the TexasFlood.org flood viewer is to assist individuals in quickly assessing the potential flood risk during a flooding event and to provide basic flood information before, during and after a flood event.  The data in the flood viewer represents the best available information provided to the Texas Water Development Board (TWDB) by its data contributors.  The information on this viewer may not be displayed in real-time and should not be considered an “exact” representation of conditions in your area.  Neither the State of Texas nor the TWDB assumes any legal liability or responsibility or makes any guarantees or warranties as to the accuracy, completeness or suitability of the information for any particular purpose. If you have any questions, please contact us at:  https://tnris.org/contact/"**

**Comment by christoball** [comment]
The disclaimer could look something like the attached mockup. Doesn't have to be exact, whatever is simplest for you.

**Comment by sashahart** [comment]
The mockup looks good to me.

It will also be necessary to define when this popup should appear and to consider how that will be implemented. For example, if you want to set a cookie that will come with its own caveats, as will showing the same popup every time the page is loaded. 

If you would like me to take sole responsibility for quickly implementing this or any other small UI changes beyond what has already been discussed, we need to have a somewhat broader discussion about process which probably shouldn't happen on the issue tracker.

**Comment by sashahart** [comment]
See #105 for a prototype of this, it won't merge without some feedback to ensure it looks like what you want.

**Comment by wilsaj** [comment]
deployed - but with an ugly encoding issue (see #110)

**Comment by sashahart** [comment]
#110 resolved. Can Chris, Miguel, or whoever is appropriate by TNRIS' lights examine whether the deployed disclaimer looks good and then deploy?

**Comment by mpavon66** [comment]
@sashahart @wilsaj @christoball @geochick Thanks to everyone that worked on this one. Acting EA should be happy it is implemented.
