### ISSUE TITLE
Reevaluate weather animation performance (Tier 2)

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/flood#117]
review the current radar weather animation and determine if the slow performance is due its' implementation within the app or if the aeris's service is simply slow. Rework to improve performance. If the service is simply too slow, switch to a non-animated doppler service to speed things up.

**Comment by adambreznicky** [comment]
ref issue #82

**Comment by adambreznicky** [comment]
look into mesonet weather, who is their provider?
also try contacting Aeris' support for suggestions/help

**Comment by adambreznicky** [comment]
aeri's service is high performance. the load issues were related to the method by which the animation was created client side - using 21 separate server calls to create 20 separate tile layers and cycling through them. This also required a large use of our map units credits. 
to fix performance, i made a single, static raster layer the default radar layer with an animation button option which would then cycle through 5 (approx 1 hour apart) layers. 
also added a timestamp display for each radar instance.

**Comment by DavidHickman** [comment]
fixed in 2c5c950032289de09be45aabd66ce3d3e7295f0b
