### ISSUE TITLE
Unsubscribe Functionality (Tier 2)

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/flood#118]
Current SMS unsubscribe functionality relies on AWS reply text 'stop' which adds users to the opt-out list. This disables their ability to receives sms messages - period - and doesn't account for the option to unsubscribe from a specific gauge only. It would currently require dev team to manage subscriptions.
Research if AWS has some out of the box functionality to handle this situation.
Alternatively, create an unsubscribe page which can be linked to from the app (subscribe dialog) and from the initial confirmation sms message. The page would allow a user to input a phone number (and/or email address). The page would then list the topics currently subscribed to and then the user could pick-and-choose which ones to then unsubscribe from (checkboxes?).

**Comment by DavidHickman** [comment]
Fixed in 3a1beabedcb55c2e5530b9e2d3e25451615919fc
