### ISSUE TITLE
Subscription Disclaimer (Tier 2)

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/flood#119]
Speak with the legal team to get specific wording for the subscription disclaimer on the Subscribe dialog. I feel as though it should explicitly disclose the imperfection of the app and demand users utilize all available resources of information in emergency situations (don't just rely on the app/notifications)

**Comment by JasonKleinert** [comment]
Closing this one because the subscribe dialog has been deprecated. Updated disclaimer language has been added to the site disclaimer and about sections.
