### ISSUE TITLE
Confirmation link to gage in map (Tier 3)

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/flood#123]
Confirmation SMS has URL to link to app. Enhance to also zoom and center the map on the specific gage subscribed to when clicked.

**Comment by adambreznicky** [comment]
confirmation sms updated in tier 2 to include link to the app. just not the map part of it.

**Comment by DavidHickman** [comment]
This now links to the "Manage Your Alerts" section of the page, which seems like the correct behavior. We could add a second link (might create multiple text messages) or a composite route, but I would suggest closing the issue for now and gathering feedback during beta before making further changes.
