### ISSUE TITLE
add favicon (Tier 1)

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/flood#124]
add a favicon. i dont know if one previously existed but the app is looking for one.

**Comment by adambreznicky** [comment]
https://github.com/HenrikJoreteg/hjs-webpack/issues/24
 "
If you basically just want to require a file so webpack knows about it, the following syntax will copy the favicon to the out directory (at the root) but leave the name unchanged: require('file?name=favicon.ico!./real/path/to/your/favicon.ico')
"

**Comment by DavidHickman** [comment]
Issue fixed in 3d07e4d223cd8c74865f93d5545ebeadcd572ded
