### ISSUE TITLE
address and geolocation locator (tier 3)

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/flood#127]
for common users who are not map oriented and just want to know which flood 'gages' are relevant to them, create a 'Find Me' or 'Find my House' dialog so the user can use geolocation or enter their address. i imagine the map would mark that location, zoom to it, and identify a few relevant (upstream) 'gages' suggesting they should be subscribed to.

**Comment by DavidHickman** [comment]
Bing address search is already provided with the magnifying glass. We still need to add the geolocation.

**Comment by DavidHickman** [comment]
Geolocator added 7b664d91d85944241b6748fea3a3a4dddf62db20
