### ISSUE TITLE
Add ability to hide sidebar in desktop view

### ISSUE THREAD

**Issue by DavidHickman** [TNRIS/flood#128]
The sidebar greatly reduced the visible map area on the kiosk display during the Water for Texas conference. The desktop display should have similar functionality to the mobile display, but default to open.

**Comment by DavidHickman** [comment]
This will likely become a new view specifically for the kiosk, unless the replacement for react-mdl makes this an easier implementation.

**Comment by JasonKleinert** [comment]
complete with commit 3e35cf638af4d8e14e04874bdbecf53bd685c187

Looks pretty good to me but needs thorough testing
