### ISSUE TITLE
Replace React-MDL with Material Design Components

### ISSUE THREAD

**Issue by DavidHickman** [TNRIS/flood#140]
[React-MDL](https://github.com/react-mdl/react-mdl) is now officially deprecated. The authors recommend using [Material Design Components](https://github.com/material-components/material-components-web) instead.

We need to investigate the time and effort required to refactor the code to use Material Design Components or find an alternative library with ongoing support.

**Comment by adambreznicky** [comment]
updated to use Foundation without any react middleware
