### ISSUE TITLE
share functionality

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/flood#144]
![selection_038](https://cloud.githubusercontent.com/assets/5650145/25189269/4a32eb3c-24ee-11e7-8bff-04f8e5baa255.png)

add share functionality. example from parkadelphia.com in image. maybe options for sharing on facebook, twitter, reddit, email, and copy link like they have...

**Comment by DavidHickman** [comment]
Twitter share functionality has been added. More options can be added in future phases.

- [ ] Twitter

- [ ] Facebook

- [ ] Email

- [ ] Instagram

**Comment by adambreznicky** [comment]
Let's add facebook, instagram, and copy link to start

**Comment by JasonKleinert** [comment]
Added facebook and email share buttons. let's revisit this one later to ad more.
