### ISSUE TITLE
Strange Browser Behavior in Firefox and Edge Browser

### ISSUE THREAD

**Issue by rwade2126** [TNRIS/flood#147]
To recreate the issue try the following.  
1) Open google chrome.  
2) Type url: https://develop.texasflood.org
3) Zoom in and pan around.
4) Copy url from Chrome
5) Open edge or firefox browser and paste link into browser.

This will usually screw up the view.  If it doesn't, paste it again into another tab.  It weirds out on me almost every time.

**Comment by JasonKleinert** [comment]
Fixed with commit 36bbd8a80ec8dffda5a7fd41f9dd713211129b4c
