### ISSUE TITLE
CartoDB - nws_ahps_gauges_texas mysterious sync failure

### ISSUE THREAD

**Issue by jseppi** [TNRIS/flood#15]
This morning the nws_ahps_gagues_texas auto-sync table was completely empty. I clicked the "Sync now" link in the CartoDB web UI and it successfully grabbed the data.
Obviously a big part of this project is going to be managing these types of sync problems.

**Comment by wilsaj** [comment]
This is a big reason for implementing #46

**Comment by sashahart** [comment]
#46 is closed and based on the belief that we are using pipeline to push now, I don't think we are using sync for CartoDB anymore.
