### ISSUE TITLE
comments from AW

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/flood#151]
First, a boring legal thing - in viewer-details page:
"(Note: TNRIS maintains a strict privacy policy and will never, under any circumstance, share or disclose a user’s contact information with any other entities or utilize their contact information for any purpose other than that for which the user has signed up.)" 

^ That seems a bit off, because:
- you need to necessarily share info with AWS
- "never, under any circumstance" is a lot to promise and probably needs to be wrapped in legal CYA 
- privacy policy should be published or linked somewhere
case in point: the app is currently leaking users' contact information

but other then that it looks pretty solid
also, gauge is misspelled

**Comment by DavidHickman** [comment]
TWDB Privacy Policy:
http://www.twdb.texas.gov/policies/site/index.asp
