### ISSUE TITLE
Changes to Disclaimer

### ISSUE THREAD

**Issue by rwade2126** [TNRIS/flood#154]
Please modify the disclaimer to read:

The data and information presented in this viewer is the best available information provided to the Texas Water Development Board (TWDB) by its data contributors. The information may not be represented in real-time and should not be considered as exact conditions in your area. Neither the State of Texas nor the Texas Water Development Board (TWDB) assumes any legal liability or responsibility or makes any guarantees or warranties as to the accuracy, completeness, or suitability of the information for any purpose. 

By using this viewer or subscribing to a gage or gages, you agree to release and hold harmless TWDB and its respective representatives, agents, successors, assigns, employees, officers and directors, from any and all liability, for loss, harm, damage, injury, cost or expense whatsoever including without limitation, property damage, personal injury and/or death which may occur in connection with the application service.

If you have any questions, please contact us at https://tnris.org/contact/

**Comment by JasonKleinert** [comment]
Updated and closed in commit 8de96f53e7a66fa0de8e2acad8b4ef7069c4779c
