### ISSUE TITLE
Weather alert popup too large on mobile

### ISSUE THREAD

**Issue by JasonKleinert** [TNRIS/flood#163]
When a weather alert is particularly long the popup becomes  very large and the map zooms out pretty far. When the popup is closed you are often left somewhere in Canada. Consider making the popup a consistent scrollable size.

**Comment by rwade2126** [comment]
This was a pretty big issue during Harvey.  I would like to move this to a priority fix.  Thanks -RW

**Comment by DavidHickman** [comment]
fixed in c59e12946dfd01bc4e64930c8f2e803ed989dfc4

**Comment by DavidHickman** [comment]
closed by https://github.com/TNRIS/flood/commit/20d4572c1d8f1cb74b0b1f77b54b566a0131491c
