### ISSUE TITLE
ESRI streets goes black at highest zoom level

### ISSUE THREAD

**Issue by JasonKleinert** [TNRIS/flood#165]
The Streets layer seems to lack tiles at our highest zoom level. The satellite and hybrid layers are good at this level, but ESRI World Streets goes bllack when zoomed all the way down.

**Comment by JasonKleinert** [comment]
This seems to be caused by setting datectRetina: true in Leaflet TileLayer options. This is set in src/reducers/baselayers.es, line 16. Setting this to false will resolve the issue.

**Comment by DavidHickman** [comment]
fixed in https://github.com/TNRIS/flood/commit/fb6a08f3791a4aa97f86b03abab2c750ca604b97

**Comment by DavidHickman** [comment]
closed by https://github.com/TNRIS/flood/commit/20d4572c1d8f1cb74b0b1f77b54b566a0131491c
