### ISSUE TITLE
Update lake charts to versions requested by WSC

### ISSUE THREAD

**Issue by JasonKleinert** [TNRIS/flood#168]
The lake charts are requested to be sourced from: [https://waterdatafortexas.org/reservoirs/flood](https://waterdatafortexas.org/reservoirs/flood) instead of the current source: [https://waterdatafortexas.org/reservoirs/individual/houston](https://waterdatafortexas.org/reservoirs/individual/houston) as per request from WSC below. We are awaiting confirmation of the correct url to pull the charts from. The path will need to be updated in: `flood/src/components/LakeConditionsPopup.jsx`
>Hey Erik,
 
>I’m not sure who the right person to ask about this, so I’m hoping that you can point  me in the right direction/help me out.
 
>On the Lake Conditions layer of the flood map viewer, when you click on a reservoir you get taken to the graph from the Reservoirs page of Water Data for Texas (https://waterdatafortexas.org/reservoirs/individual/houston). These data are averaged daily and therefore don’t present the an accurate picture of reservoir conditions at a particular time. The map viewer previously pointed to the Flooding page of WD4T, and that’s where folks that visit the viewer should be directed. Here’s the link:  https://waterdatafortexas.org/reservoirs/flood.  
 
>I’m guessing that when there was an update to the viewer that something happened and the flooding page and the general reservoirs page of WD4T got switched out. Can you help me sort out getting things back in order?
 
>Thanks!
s.

**Comment by solomon-negusse** [comment]
Hi @JasonKleinert we have an api for the instantaneous water levels you need for this. Here is an example: https://waterdatafortexas.org/reservoirs/api/individual/addicks/recent-elevations-chart.
We made a few changes to the d3 chart on the front-end that we haven't ported to these matplotlib figures. I'll make those updates later today or early next week and let you know.

**Comment by JasonKleinert** [comment]
Ok, thanks Solomon. We can resource to that endpoint, this is where we were pulling from in version 1. Should we wait for your update before redeploying?

**Comment by solomon-negusse** [comment]
Probably best to wait. The change will affect flood control reservoirs so I want to make sure we present consistent information on both versions of the charts.

**Comment by solomon-negusse** [comment]
The charts are ready. Let me know if you need any tweaks to make them fit your styles.

**Comment by JasonKleinert** [comment]
Thank you.
This is what the chart looks like at: [https://waterdatafortexas.org/reservoirs/api/individual/somerville/recent-elevations-chart](https://waterdatafortexas.org/reservoirs/api/individual/somerville/recent-elevations-chart)
![image](https://user-images.githubusercontent.com/5649664/30499244-4de6e6b0-9a1f-11e7-8a23-69093bacaf28.png)
Is this the correct chart? Will there be a chart for all lakes all the time, or only for ones that are flooding? We need a full set of charts for all the lakes for the popups in the flood viewer.

**Comment by solomon-negusse** [comment]
No problem. Yes, that's the correct chart and there should be charts for all lakes. We update the data every 15 minutes.

**Comment by solomon-negusse** [comment]
If you guys ever want to plot the chart on your end, we have api for the time-series data and can share the d3 chart code.

**Comment by JasonKleinert** [comment]
Thanks for all your help @solomon-negusse getting this resolved. Could you share a link to the api and the d3 code?

**Comment by solomon-negusse** [comment]
No problem Jason. I have added you to TNRIS team in WSC github account to access reservoirs repo and d3 code (https://github.com/twdb/swis/blob/master/swis/static/js/swis/flood.js). 
Here are the endpoints for data displayed on the chart:
**water level time-series:**
`https://waterdatafortexas.org/reservoirs/api/individual/{lake-url-name}/recent-elevations`
example: https://waterdatafortexas.org/reservoirs/api/individual/choke-canyon/recent-elevations

**static elevations (top of dam, emergency spillway, etc.):**
`https://waterdatafortexas.org/reservoirs/api/info/{lake-url-name}`
example: https://waterdatafortexas.org/reservoirs/api/info/addicks

Let me know if you have any questions as you look thru the code.
