### ISSUE TITLE
Flood Gauge charts coming from Symantec SSL Cert

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/flood#172]
![screenshot from 2018-02-07 15-15-50](https://user-images.githubusercontent.com/5650145/35942941-10727a68-0c1d-11e8-948f-5d0003f741e3.png)
Upon clicking any flood gauge popup, it retrieves the gauges' chart from NWS's website which is a weather.gov domain. This puts a Warning in the console because Chrome will be doing away with marking Symantec SSL Certificates as secure and weather.gov's cert hasn't been updated to be non-symantec. Not much we can do about it except maybe inquire with NWS about their plans to update their certificate to adhere to the new rules. If they don't update it, the charts will not load in Chrome when the change is officially implemented.
I imagine that if the weather.gov's cert is not updated, and Chrome implements the change, the quick fix will be to change the 'src' reference for these charts to be regular, non-secure http. Not a huge deal but will make us lose our nice little green security lock in Chrome. Only other alternative is to make our own charts or manage our own chart images somehow.... not a practical solution.

**Comment by jseppi** [comment]
From a colleague:

> note that it's Chrome 70 which will distrust it
I'm currently running Chrome 64
that's like 36 weeks away
Estimated August 30th: https://www.chromium.org/developers/calendar

So hopefully weather.gov is aware and will make that switch before the end of August 🤞

**Comment by adambreznicky** [comment]
weather.gov updated their cert with a forced 443 redirect
