### ISSUE TITLE
Sidebar 'Action Feed'

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/flood#174]
Add a collapsible section on the sidebar like Map Layers and My Alerts for an 'Action Feed' or Newsfeed which displays the 'x' number of recent tweets from @TexasFloodOrg twitter account... this will serve as a basic little reference of recent action and whats been going on with the gauges recently. Add link to @TexasFloodOrg twitter page also

**Comment by JasonKleinert** [comment]
completed with commit d0c8fd3b38aa543bfa61c8b4d85c1169419d83f2

**Comment by JasonKleinert** [comment]
bug - sidebar doesn't scroll on iphones

**Comment by JasonKleinert** [comment]
fixed bug with commit 7208403234479d70e212c9638e80e9bec0949919
