### ISSUE TITLE
final bugs from review

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/flood#192]
- [x] horizontal turned ipad air, 3: sidebar doesn't work. they are os 10.3.3
- [x] maybe keep halos all the same size?
- [x] 'About' modal: add subtle, fixed 'X' to close modal
- [x] DWYT2 shows action prediction inaccurately. pipeline issue?
- [x] rwade unsubscribe not working. had weird key in his federated identity dataset. fluke? test with other pre-existing users

**Comment by adambreznicky** [comment]
rwade's unsubscribe seems to be a fluke. it is most likely a remnant from previous testing before alerts were finalized. have tested multiple historical accounts converting to the new predictive format with no issues. his situation is not replicable and is considered an official fluke.

dwyt2 seemed to be a pipeline hiccup from excessive data size in the RDS. we re-deployed the pipeline with a longer but more aggressive  frequency cleanup to resolve this issue.

we will ignore the halo size suggestion for now as we believe it is straight forward to the user. we can revisit if we get enough negative feedback.

**Comment by JasonKleinert** [comment]
resolved ipad/tablet bug with commit 2c8757b7a4ae559c814ceed0bf9a92d5ffacc257

**Comment by JasonKleinert** [comment]
added fixed 'x' to close about-modal with commit 0f3796474e9d7176daf16aa2d917ead2db10cc8a
