### ISSUE TITLE
Resources Footer Links

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/flood#202]
the links in the resources section of the footer are broken, TWDB moved all the information to a different location. I think these are the correct links. 

Preparing Before a Flood - https://www.texasflood.org/flood-basics/index.html
Being Safe During a Flood - https://www.texasflood.org/emergency-prep/index.html
Recovering After a Flood - https://www.texasflood.org/recovery/index.html

At the time of issues creation, i have not heard back from Jeff or Matt about the correct links.

**Comment by ctrepka** [comment]
fixed and closed

https://github.com/TNRIS/flood/commit/869031f4f72300eb9b3baad4ede47583a618b68b
