### ISSUE TITLE
Aeris Attribution

### ISSUE THREAD

**Issue by jseppi** [TNRIS/flood#30]
Slightly hard to understand, but we might to display the Aeris logo on the page.

http://www.aerisweather.com/support/docs/credit/ says:

> While some of our products and services can be used commercially without requiring attribution, most products including the AerisWeather API and Aeris Maps require proper attribution by using any one or a combination of the allowed AerisWeather marks as described below.

**Comment by wilsaj** [comment]
Seems clear to me that we satisfy the attribution requirements if we include the name without a logo:
> "... require proper attribution by using any one or a combination of the allowed AerisWeather marks as described below..."

> "AerisWeather's marks include, but are not limited to, the Aeris name, AerisWeather name and logo..."

**Comment by wilsaj** [comment]
Before closing, the leaflet attribution should be changed to "AerisWeather" with a link to their site.
