### ISSUE TITLE
Aeris Subscription

### ISSUE THREAD

**Issue by jseppi** [TNRIS/flood#31]
We need to purchase an Aeris subscription. Until then advisory layers and api queries (like for flood alerts) won't be available.

**Comment by wilsaj** [comment]
A call with their sales folk is scheduled for Monday (3/28) afternoon. We'll also ask about attribution (#30)

**Comment by sashahart** [comment]
This was blocked on a meeting that happened Mar 28. Is it still an open issue?

**Comment by wilsaj** [comment]
Nope
