### ISSUE TITLE
WDFT Reservoir Conditions

### ISSUE THREAD

**Issue by wilsaj** [TNRIS/flood#38]
Lake conditions
# source
- preliminary data available at http://waterdatafortexas.org/reservoirs/recent-conditions.json
- there is a better real-time service is being currently worked on by WDFT staff that will provide height above conservation pool elevation and height to the top of the dam
# challenges
- flood stage is not a good proxy for flood danger 
  - there are a lot of other factors that determine likelihood of flood releases and these are different for each reservoir
  - rating curves stop at conservation pool elevation, so we don't have a good estimate of flood pool volume

**Comment by sashahart** [comment]
Which parts of this data are we going to use? From context I assume that we will use, when provided, height above conservation pool elevation, and height to the top of the dam. What else will we need to import from this data source?

Any kinds of cleanup, derived calculations, or sanity checks you specifically would like to do on this WDFT reservoir data?

Is this data going to feed both notifications and map layer(s), or just map layers? If reservoir conditions are not very informative about flood danger until we have other (e.g. reservoir-specific) information, it could simplify things not to have to do notifications on reservoir conditions initially.

**Comment by wilsaj** [comment]
> Which parts of this data are we going to use? From context I assume that we will use, when provided, height above conservation pool elevation, and height to the top of the dam. What else will we need to import from this data source?
> 
> Any kinds of cleanup, derived calculations, or sanity checks you specifically would like to do on this WDFT reservoir data?

Hard to get to specifics at the moment since the data doesn't exist yet, but from what I understand the info will be more or less what we see in the recent-conditions.json with some additional info. At most, we may need to make one or two simple additional calculations like deriving percentage based on flood pool values.

> Is this data going to feed both notifications and map layer(s), or just map layers? If reservoir conditions are not very informative about flood danger until we have other (e.g. reservoir-specific) information, it could simplify things not to have to do notifications on reservoir conditions initially.

Just map layers. Notifications are only going to be generated by the NWS flood rated gauges.

**Comment by sashahart** [comment]
I might take it that this work is more or less complete as our "lake conditions" layer. Is that accurate? If not, what else do we need to do to satisfy this part of MVP?

**Comment by wilsaj** [comment]
Right now, this relies on CartoDB's sync table but that can sometimes error out and gets stuck so it stops updating. We need a more reliable - either adding some form of error detection to the sync table functionality or hooking this into the data pipeline where that sort of thing can be done.
