### ISSUE TITLE
Rain Forecast

### ISSUE THREAD

**Issue by wilsaj** [TNRIS/flood#40]
Map layer showing forecast precipitation
## source
- Aeris provides a layer with some rain and radar forecasts that we can use for MVP
  - [ ] these layers require subscription, so waiting on procurement (#31)
  - [x] integrate into map viewer
- There are some more official forecasts provided by NOAA and NWS but they will require more work than we have time for.

**Comment by sashahart** [comment]
Since this was pending #31 which is now closed, and we do have a forecast layer, I believe this may be closeable or at least not blocked.

**Comment by wilsaj** [comment]
Yep, this can be closed
