### ISSUE TITLE
TxDot Road Closures

### ISSUE THREAD

**Issue by wilsaj** [TNRIS/flood#41]
Real-time road closure information maintained by TxDOT for [DriveTexas](http://drivetexas.org/)
## source
- Looks to be cached and served out for the Drive Texas app by a service called MapLarge that makes it difficult to get to the raw data
## status
- @mpavon in communication with TxDOT about allowing us access to the dataset. Discussions have been slow going due to recent re-org at TxDOT.

**Comment by sashahart** [comment]
I assume this is to be consumed by a map layer (assuming we get access).

**Comment by wilsaj** [comment]
We'll most likely be indirectly consuming their road closure data and generating our own CartoDB layer rather than reusing the existing MapLarge services for two reasons:

1. TxDOT has expressed concern over scalability issues that our app might cause. They've done a lot of work to get things good and load-tested, but they still don't want us (or anyone) sending a ton of additional traffic their way.
2. We'll have the ability to reshape and symbolize the data in a way that makes sense for our application


We are hoping to get access to read-only access to an an ArcGIS server that contains the raw data, so that should be able to give us the data as geojson features (points and lines)

**Comment by mitchellryant** [comment]
Contact info and emails were lost so we needed to determine who owned the data and who we were working with.

Email to AppGeo to determine who owns data.

Happy Monday? I hope. I have a quick question for you regarding DriveTexas. We are having a little bit of difficulty getting this information out of TxDOT so we thought we would try you. Do you know who (district/division/office) is in charge of the actual data, like road conditions, that is in DriveTexas?

Reply

Sure, DriveTexas is run by the Travel Information Division.  The data itself is collected across all of the districts and compiled by the main department with support from TxDOT IT.  Are you looking for something in particular?

**Comment by mitchellryant** [comment]
Contact info and emails were lost so we needed to determine who owned the data and who we were working with.

Email to NTTData to determine who we were working with.

Almost a year ago we discussed adding the drive texas road closures to the flood app we have. We were working with you, Pennington, and someone else. Who was that third person? Apparently no one wrote that name down.

Reply:

Hey Ryan.  I hope all is well on your end.  Currently, the effort to open API access to DriveTexas is being led by Brent Eastman in the IT Strategy area.  Back many months ago, it was just James Pennington and I and the business unit from the Travel Division.  That team consists of Martha Martin, Joe Hurley and Bryan Watson.  You may be thinking of Bryan Watson.  I think he has been leading the effort to get the data sharing agreement signed.
 
Let me know if you need anything else…..

**Comment by adambreznicky** [comment]
James Johnson of NTT for TxDOT supplied a feature service hosted in AGOL with statewide road closures. Awaiting further discussion as per reliability, maintenance schedule, and potential formal agreement before implementing this data:
http://txdot.maps.arcgis.com/home/item.html?id=baad58d4d3bb4c159d0d659325429bc4

**Comment by mitchellryant** [comment]
Question:
I have a couple more question about the service. 
who would maintain it? and what is the frequency it will be updated?

Reply from James Johnson:
I met with TxDOT IT last week and we are moving forward with the proposal from AppGeo to build out a geojson data feed from DriveTexas.  We should be able to get this going pretty quickly.  I’ll send you a file to test.  The geojson file from DriveTexas will contain the same information that is found on the DriveTexas site and will be refreshed when the DriveTexas site is refreshed with data.  This will ensure the real-time requirement for road condition data in DriveTexas.
 
The data will not be pushed to the AGOL Open Data Portal at this time.
