### ISSUE TITLE
SMS Notification System

### ISSUE THREAD

**Issue by wilsaj** [TNRIS/flood#45]
# SMS Notification System
## needs
- Support people subscribing a phone number to a flood gauge to receive updates when a gauge enters a flood stage or is predicted to. This first subscription step will be triggered from the front-end via HTTP request.
- The data will be scraped/updated periodically from National Weather Service in the data pipeline (#36).
  - Data pipeline will trigger this notification system, which should send out messages to every subscribed number telling them what’s up. Messages should be able to contain a URL with more info.
- Twilio and Plivo look like solid third party services handling the message sending part. AWS SNS service can kind of do this, but is really limited and missing a lot of features.
- Needs to handle user flow (“You’ve subscribed to updates from TXFLOOD… send STOP to cancel”).
- Both Twilio and Plivo handle this automatically.
- Should not spam or blow up anyone's phone.
## status
- [ ] research available third-party SMS systems
  - [ ] procure services (3-4 week lag time)
- [ ] design
- [ ] implementation
- [ ] deployment

**Comment by sashahart** [comment]
per earlier communication this may (need to) be deferred until after MVP

**Comment by mpavon66** [comment]
Is it possible to have a separate disclaimer for users who sign up for the emergency notification messages (end users of the Twilio service)?  The answer to that, I think, would be a YES, that is possible, additionally lets consider it preferable and a better option than trying to amalgamate both disclaimers (viewer and notification) together. It would also be fearer, so not-subscribers to the notification system, do not have to agree to Twilio’s terms of use language. It can be that only subscribers at the time of subscription to notifications need to agree to the terms to proceed.

**Comment by sashahart** [comment]
@mpavon66: Probably whatever you want is possible, as long as it is well defined. 

However, in the interests of trying to keep issues small and actionable, I'd like to reserve this issue for broader architectural issues which touch on the backend.

Regarding the disclaimer, would you mind creating a couple new issues separate from this one?

A: a new issue describing what you want done with the existing viewer disclaimer in the near future. Do you want to change the words, remove it, move it around, change its appearance, etc.? I propose to put whatever details you have for the disclaimer in this new issue and if there are design details I'll let you hash those out with Chris or whoever before I seek clarification or try to implement the given design.

B: a new issue, addressed to the more distant future when there is an actual notification system, where the future design of the disclaimer for the notification system can be hashed out by TNRIS  people. This should be as specific as possible on what will trigger the disclaimer being shown. For that matter, we don't even have a documented interface design for what notification subscription should look like. I will be happy to offer feedback on what is more or less feasible at a technical level once there is a sort of basic idea of how the workflow will be for the user.

Please let me know if you have any questions, I appreciate your willingness to engage here.
