### ISSUE TITLE
Lake Conditions Map Layer

### ISSUE THREAD

**Issue by wilsaj** [TNRIS/flood#47]
- map layer to represent WDFT lake conditions, based on flood pool elevation #38 
- Yujuin's recommendation is equally divide the distance from conservation pool top to of them dam into 5 levels: 0-20%, 20-40%, 40-60%, 60-80%, and over 80%

## status
- [x] waiting on flood pool information to be available via WDFT

**Comment by sashahart** [comment]
How would the frontend like to consume this (e.g. import to something like CartoDB)?

**Comment by wilsaj** [comment]
The front-end will consume as a CartoDB layer.

As an approximation, this is what it looks like when colored based on existing info about percent-full instead of flood pool: https://tnris-twdb.cartodb.com/u/tnris/viz/e863ba1a-c14a-11e5-b328-0e31c9be1b51/public_map

**Comment by wilsaj** [comment]
closing - this is in now
