### ISSUE TITLE
Legal Review and Disclaimers

### ISSUE THREAD

**Issue by wilsaj** [TNRIS/flood#49]
- need to get advice from TWDB Legal department on what language and disclaimers need to be on the site
- specifically, features like real-time SMS notifications raise questions with regard to liability

**Comment by wilsaj** [comment]
From legal dept:

> The intent of the flood viewer is to assist individuals in quickly finding general flood information before, during and after a flood event.  The data in the flood viewer represents the best available information provided by the TWDB and third-party cooperators of the TWDB.  The information should not be relied upon as exact data at any given point in time.  The flood zone viewer should not be used as the primary resource for making official flood zone determinations, as it is not an official flood map.  Neither the State of Texas nor the TWDB assumes any legal liability or responsibility or makes any guarantees or warranties as to the accuracy, completeness or suitability of the information for any particular purpose. The TWDB systematically revises or removes data discovered to be incorrect.  If you find inaccurate information or have questions, please contact us at:  https://tnris.org/contact/

**Comment by mpavon** [comment]
Great, I was about to put my first comments on Github ever, and you beat me by two hours, Thanks.

**Comment by wilsaj** [comment]
sorry!

**Comment by wilsaj** [comment]
@christoball you have any thoughts on where/how to fit in this text?

**Comment by christoball** [comment]
@wilsaj How prominent does it have to be?

What about a link in the bottom next to the twdb logo that opens up a modal?

![image](https://cloud.githubusercontent.com/assets/1877550/15691411/2dadc44e-274e-11e6-96df-6e92837344a0.png)

**Comment by wilsaj** [comment]
I like that

**Comment by wilsaj** [comment]
Maybe just label it "About" ?

**Comment by christoball** [comment]
I think it needs to be specific that's it's legal stuff. Richard suggested just using 'Disclaimer'.

FYI - Richard has new legal language that he plans to send later today.

**Comment by christoball** [comment]
New language from @rwade2126:
"The intent of the TexasFlood.org flood viewer is to assist individuals in quickly assessing the potential flood risk during a flooding event and to provide basic flood information before, during and after a flood event.  The data in the flood viewer represents the best available information provided to the Texas Water Development Board (TWDB) by its data contributors.  The information on this viewer may not be displayed in real-time and should not be considered an “exact” representation of conditions in your area.  Neither the State of Texas nor the TWDB assumes any legal liability or responsibility or makes any guarantees or warranties as to the accuracy, completeness or suitability of the information for any particular purpose. If you have any questions, please contact us at:  https://tnris.org/contact/"

**Comment by sashahart** [comment]
The implementation of this seems to be in #100
