### ISSUE TITLE
CartoDB Layers - Refresh layer tokens on a timer

### ISSUE THREAD

**Issue by jseppi** [TNRIS/flood#50]
CartoDB layers should re-request their layerids (via post to `https://tnris.cartodb.com/api/v1/map/`) on a timer. Probably a 2 to 4 hour timer would work to ensure that the tile layers don't start to error out after long periods of user inactivity.

**Comment by wilsaj** [comment]
Also for layers based on realtime-ish data, we'll want a shorter interval so the data stays fresh (and so clean clean).
