### ISSUE TITLE
atxfloods.com road closures

### ISSUE THREAD

**Issue by wilsaj** [TNRIS/flood#54]
Road closure data from https://www.atxfloods.com/
## source
- data published in XML format and pretty easy to parse (see: https://github.com/TNRIS/atx-low-water-crossings) 
- coverage is limited to only a few counties in central Texas
- might end up as a backup data source for the Road Closures layer if we can't get TxDOT road closures off the ground

**Comment by adambreznicky** [comment]
James Johnson of NTT for TxDOT supplied a feature service hosted in AGOL with statewide road closures. Awaiting further discussion as per reliability, maintenance schedule, and potential formal agreement before implementing this data:
http://txdot.maps.arcgis.com/home/item.html?id=baad58d4d3bb4c159d0d659325429bc4
