### ISSUE TITLE
improve front-end time-to-render

### ISSUE THREAD

**Issue by wilsaj** [TNRIS/flood#57]
absolute garbage at the moment, mostly due to a combination of S3 being slow and a single large scripts.js file that includes a bunch of vendor'd code:

![image](https://cloud.githubusercontent.com/assets/303866/14093584/857a2ea4-f514-11e5-8f8c-48f46ebf97f5.png)

Some time before launch this needs to be fixed with some combination of:
- deploying on cloudfront
- code splitting
- tree shaking (if we wanna get real fance)
- displaying something other than blank screen while the app loads

**Comment by DavidHickman** [comment]
I ran some preliminary load tests this morning on develop.texasflood.org. The site handled 10,000 total and concurrent requests distributed across three global AWS regions. The tests reported zero errors with an average load time of 0.351 seconds; max load time was 1.225 seconds.
