### ISSUE TITLE
If dev console is closed, clicking fullscreen button leads to black screen

### ISSUE THREAD

**Issue by jseppi** [TNRIS/flood#67]
Windows 10, Chrome

Clicking the fullscreen button on the leads to a fullscreen black box (and also showing the browser's "Press ESC to exit fullscreen" message). No errors appear to be thrown.

If the dev console is open, the fullscreen button works as expected. 

Fullscreen button works as expected in Windows 10 Firefox.

**Comment by sashahart** [comment]
I can confirm this is still happening, if you use the fullscreen button we are presenting as part of the UI.

It doesn't happen using the browser's fullscreen feature (e.g. press F11) or maximizing/resizing the window. Which raises the question in my mind of why we even need the fullscreen button. It would address this issue and also simplify the UI if we simply removed the fullscreen button, which many slippy maps don't have anyway.

**Comment by wilsaj** [comment]
I agree

**Comment by sashahart** [comment]
I believe removing the button has resolved this issue, thanks!
