### ISSUE TITLE
IE - Needs Promise polyfill

### ISSUE THREAD

**Issue by jseppi** [TNRIS/flood#68]
Windows, IE 11 (and also previous versions).

Promise is undefined, need polyfill.

![image](https://cloud.githubusercontent.com/assets/697848/14227205/768d9c8a-f8bd-11e5-97c3-cd68eae4d8dd.png)

**Comment by jseppi** [comment]
I heard your soul lives on until all the issues you've created have been closed.

**Comment by wilsaj** [comment]
"Sssshhhhhh... You hear that? Why that there is ol' Seppi rattling around in the map stacks, come to check on his issues."
