### ISSUE TITLE
CartoDB: user-level access & permissions

### ISSUE THREAD

**Issue by sarasafavi** [TNRIS/flood#69]
To implement #46, we need an API token tied to the TNRIS CartoDB account. 

For security, we should create a limited user only for use in this project. Ideally, I'd like this user (and likewise, this user's token) to [only have UPDATE/INSERT access](http://docs.cartodb.com/cartodb-platform/sql-api/tips-and-tricks/#is-there-an-in-between-where-a-user-can-write-but-not-drop-or-delete) to the table(s) used in this project. We can use an admin user to create & delete table(s) as needed.

Multiuser access is only available to Enterprise CartoDB accounts, so this may not be possible on the current TNRIS account. The alternative just means we have a singleuser account, with one god-token that allows R/W access to all tables. That technically would still work, but we might want to avoid distributing said god-token across production servers.

**Comment by wilsaj** [comment]
We do have an enterprise CartoDB account with a few spare users, so we can spin off a separate app-specific user in our TNRIS organization and tighten down the permissions for that user.

**Comment by sarasafavi** [comment]
Perfect! That makes me a lot less worried.

**Comment by sashahart** [comment]
Now that we have the tnris-flood account, at least it shouldn't mess too much with other stuff on the TWDB account, but there doesn't seem to be any way of limiting its access any more granularly. If this is true and it's the best we can do then I think we should close this.

**Comment by sashahart** [comment]
I'll call this done, since CartoDB push is working and there are no finer-grained permissions available from CartoDB than what we are using.
