### ISSUE TITLE
DynamoDB Schema for Data Service

### ISSUE THREAD

**Issue by sashahart** [TNRIS/flood#71]
I'm making this issue for discussion of the interface that will be provided from DynamoDB to Data Service.

This could be worked out starting from higher-level considerations like what kinds of data will be stored, and what kinds of access patterns are expected. Or it could be implied by some code. Or the schema could just be given directly. Whatever. It just needs to be worked out somehow.

Dependencies of this issue include both the Data Service API itself and also the pipeline code which puts the data for Data Service into DynamoDB, and therefore needs to know about things like hash keys and range keys.

**Comment by wilsaj** [comment]
To follow on with data service discussions, I'm not thinking of these as being unified, since data are kind of hard to jam into one shape. We can even have multiple schemas / tables for different pieces of the pipeline, so we don't need to worry too much about normalizing everything up front. We'll add new tables where needed. For example for a combined NWS + USGS gauge layer:
1. a table for the NWS flood gauges  (each item is a flood gauge)
2. a table for USGS stream gauges (each item is a stream gauge)
3. a table for the combined / merged output of both of these (each item is some normalized representation of either a flood gauge or a stream gauge)

... so we can start with 1, and deal with 2 and 3 later when we come to it. If the Data Service API needs to change to accommodate the different gauge types, then we'll make those changes.

**Comment by wilsaj** [comment]
To get concrete with the NWS gauge example: We'll be querying primarily by individual gauge, so we can just have a table for NWS flood gauges with one item per gauge. Each item would be a document containing:
- all of the relevant info in the XML endpoint for the gauge (ex: http://water.weather.gov/ahps2/hydrograph_to_xml.php?gage=cart2&output=xml) 
- combined with some latitude and longitude from the `get_map_points` endpoint
- and most recent status, computed from values as read from XML


`id` would be the primary (and only) key. Example:

```
{
  "id": "CART2",
  "latitude": 32.965833,
  "longitude": -96.944167,
  "status": "action",
  "name": "Elm Fork Trinity River 2 AT Carrollton",
  "sigstages": {
    "action": { "value": 7, "units": "ft"},
    "bankfull": { "value": 8, "units": "ft"},
    "flood": { "value": 8, "units": "ft"},
    ...
  },
  "zerodatum: { "value": 431.4, "units": "ft MSL"},
  "rating": {
     "dignity": "official", 
     "data": [
        {
          "stage": {"value": 2.8, "units": "ft"},
          "flow": {"value": 0.000, "units": "kcfs"}
       },
        {
          "stage": {"value": 3.0, "units": "ft"},
          "flow": {"value": 0.010, "units": "kcfs"}
       },
        ...
      ]
  },
  ....
  "observed": {
     "data": [
        {
          "timestamp": "2016-04-05T16:15:00-00:00",
          "stage": {"value": 7.39, "units": "ft"},
          "flow": {"value": 4.74, "units": "kcfs"}
       },
     ....
   ]
  },
  "forecast": {
    "issued": "2016-04-05T12:56:00-00:00",
    "data": [
        {
          "timestamp": "2016-04-05T18:00:00-00:00", 
          "stage": {"value": 7.30, "units": "ft"},
          "flow": {"value": 4.56, "units": "kcfs"}
       },
       ...
    ]
  }
}
```

**Comment by sashahart** [comment]
I apologize if I'm repeating myself too often, but I was trying to just address what tables would be required by the frontend charting, as distinct from CartoDB map layers, notifications, or any use internal to the pipeline. 

I agree with what you said about using multiple tables to capture multiple schemas, and not worrying about normalization here. But for my own purposes, I don't even want any input on the shape of the DynamoDB tables that the frontend will be consuming for charting. I just want to know what that shape will be so that I can push the right data to the right place. You can change it however you want whenever you want and I'll just adapt a bit of pipeline. No problem.

**Comment by sashahart** [comment]
As I understand, you are saying you want a table in DynamoDB for the *latest* readings from NWS flood gauges. Also, you want this table to have essentially the same schema as what we get in the hydrograph XML.

Is this going to work for charting? Is this intended for charting only? You specifically said "layers" when you defined those tables, so I'm wondering if you aren't defining them for the purpose of pushing them to CartoDB or just for having for any purpose.

Do we need to expose the full contents of the hydrograph XML to the frontend via DynamoDB, or is this table and schema not just meant for direct consumption by the frontend?

**Comment by wilsaj** [comment]
Ok - I see what you're asking. Sorry for being dense.

So, high level considerations: For the charting API we don't need the full contents of the hydrograph XML, but we do need to know the stages and timeseries values plus a few metadata values. We want a slightly more compact version of the same data. Queries will be 1-to-1 with each gauge and they will only happen when someone clicks on a gauge point. 

So API will work something like this:

endpoint: `/api/v1/flood-gauges/<gauge_id>/`
returns:
```
{
  "id": "CART2",
  "latitude": 32.965833,
  "longitude": -96.944167,
  "status": "action",
  "name": "Elm Fork Trinity River 2 AT Carrollton",
  "sigstages": {
    "action": 7,
    "bankfull": 8,
    "flood": 8,
    ...
  },
  "units": {
    "stage": "ft",
    "flow": "kcfs",
  },
  "rating": [
        {
          "stage": 2.8,
          "flow": 0.000
       },
        {
          "stage": 3.0,
          "flow": 0.010
       },
        ...
  ],
  "observed": [
        {
          "timestamp": "2016-04-05T16:15:00-00:00",
          "stage": 7.39,
          "flow": 4.74,
       },
     ....
   ]
  },
  "forecast": {
    "issued": "2016-04-05T12:56:00-00:00",
    "data": [
        {
          "timestamp": "2016-04-05T18:00:00-00:00", 
          "stage": 7.30, 
          "flow": 4.56,
       },
       ...
    ]
  }
}
```

**Comment by wilsaj** [comment]
Ok - I see what you're asking. Sorry for being dense.

So, high level considerations: For the charting API we don't need the full contents of the hydrograph XML, but we do need to know the stages and timeseries values plus a few metadata values. We want a slightly more compact version of the same data. Queries will be 1-to-1 with each gauge and they will only happen when someone clicks on a gauge point. 

So API will work something like this:

endpoint: `/api/v1/flood-gauges/<gauge_id>/`
returns:
```
{
  "id": "CART2",
  "latitude": 32.965833,
  "longitude": -96.944167,
  "status": "action",
  "name": "Elm Fork Trinity River 2 AT Carrollton",
  "sigstages": {
    "action": 7,
    "bankfull": 8,
    "flood": 8,
    ...
  },
  "units": {
    "stage": "ft",
    "flow": "kcfs",
  },
  "rating": [
        {
          "stage": 2.8,
          "flow": 0.000
       },
        {
          "stage": 3.0,
          "flow": 0.010
       },
        ...
  ],
  "observed": [
        {
          "timestamp": "2016-04-05T16:15:00-00:00",
          "stage": 7.39,
          "flow": 4.74,
       },
     ....
   ]
  },
  "forecast": {
    "issued": "2016-04-05T12:56:00-00:00",
    "data": [
        {
          "timestamp": "2016-04-05T18:00:00-00:00", 
          "stage": 7.30, 
          "flow": 4.56,
       },
       ...
    ]
  }
}
```

**Comment by sashahart** [comment]
This issue is obsolete due to subsequent discussion, all we need is the minimum to duplicate the NWS images in a JS frontend, which should start with dummy data to nail down these issues.
