### ISSUE TITLE
graph sizing is bad when tinyphone and geocoding are used

### ISSUE THREAD

**Issue by wilsaj** [TNRIS/flood#87]
From RW & MP:

> After you search with the magnifying glass in an iphone OS system, the graphs do not display correctly, they are shown at a portion of their size and you need to scroll to see the whole graph. Without the search being used, you get the whole graph as you should.

I'm not sure I understand this - will try to get a screenshot.

**Comment by sashahart** [comment]
Does "graph" here mean the ones which pop up when you click one of the points representing a flood gauge, currently implemented as static images?

**Comment by rwade2126** [comment]
Yes,  Here is a screenshot of what happens to a graph (in this case, the Flood gage graph) after you perform a search.  To produce it on your phone, do the following:

1) open flood viewer
2) make sure flood gages layer is on.
3) press the "search" icon and type "Concan, Tx"
4) tap any of the points that may appear.

You will see that the resulting graph appears to be scaled incorrectly (cut in half in some cases)  you can actually scroll the graph. 

See attached picture.
![screenshot_20160608-163826](https://cloud.githubusercontent.com/assets/1914936/15912206/9e9814c0-2d98-11e6-8f41-cc827f519ee8.png)

**Comment by sashahart** [comment]
This is very helpful. My thought is that we can try to address this issue during the implementation of the popup that replaces this image popup.
